# -*- coding: utf-8 -*-
"""Seca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjwKH29-Vj18CwfhMkXa9JbSTAxLpp-6
"""

# monta o meu drive aqui no colab/máquina virtual
from google.colab import drive
drive.mount('/content/drive')

!cd /content/drive/MyDrive/INMET/

!ls

# carrega o csv com Pandas
import pandas as pd
df_sicor = pd.read_csv('/content/drive/MyDrive/INMET/sicor-interest-data.csv')

df_sicor

df_sicor['longitude_centroide'].max()

# no resultado da sql tem uma longitudes com valores positivos... não tem como ser aqui no Brasil...
# Então, estou assumindo que essas longitudes estão vindo sem o sinal de negativo na frente...
# Logo, posso ajustar da seguinte forma:
df_sicor['longitude_centroide'] = df_sicor['longitude_centroide'].abs()*-1

df_sicor['longitude_centroide'].max()

df_sicor['latitude_centroide'].max()

# aqui vamos aplicar um filtro nas nossas e longitude latitudes que sejam coerentes com as dimensões do brasil
df_sicor = df_sicor.loc[df_sicor['latitude_centroide'][(df_sicor['latitude_centroide'] >= -34) & (df_sicor['latitude_centroide'] <= 6)].index]

df_sicor = df_sicor.loc[df_sicor['longitude_centroide'][(df_sicor['longitude_centroide'] >= -75) & (df_sicor['longitude_centroide'] <= -33)].index]

df_sicor

# aqui filtrando apenas as cops de SOJA da nossa base em .CSV
df = df_sicor[(df_sicor['produto'] == 'soja')]

df

# Agora, vamos contar quantas vezes uma coordenada solicitou seguro
# faz a contagem por groupby
contagem = (df
    .groupby(['longitude_centroide', 'latitude_centroide']) # Agrupa as linhas do DataFrame por pares únicos de longitude, latitude.
    .size() # Conta quantas linhas existem em cada grupo
    .reset_index(name='contagem') # Transforma o resultado de Series para DataFrame, nomeando a coluna de 'contagem'
    .sort_values('contagem', ascending=False)  # Ordena do maior para o menor
)

contagem

# Quem pediu mais que 10 vezes
absurdos = contagem[contagem['contagem']> 10]

absurdos

# instalando a biblioteca que faz mapas no Python...
!pip install cartopy

# vamos ver a distribuição desses valores estranhos...
# e aqui já vou aproveitar para fazer um "mapa" em Python

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import numpy as np

proj = ccrs.PlateCarree() # nossa projeção favorita → WGS84

fig, ax = plt.subplots(figsize=(12, 10), subplot_kw={'projection': proj})

# Limites do mapa (baseado nos dados com margem)
margin = 1 # aqui é uma margem de 1° de lat e longitude em relação ao min max de lat lon
ax.set_extent([
    absurdos['longitude_centroide'].min() - margin,
    absurdos['longitude_centroide'].max() + margin,
    absurdos['latitude_centroide'].min() - margin,
    absurdos['latitude_centroide'].max() + margin
], crs=proj)

# Features do mapa
ax.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='gray')
ax.add_feature(cfeature.STATES, linewidth=0.3, edgecolor='gray', linestyle='--')
ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')

# Normalização para tamanho e cor
sizes = np.interp(absurdos['contagem'],
                  [absurdos['contagem'].min(), absurdos['contagem'].max()],
                  [10, 300])

sc = ax.scatter(
    absurdos['longitude_centroide'],
    absurdos['latitude_centroide'],
    c=absurdos['contagem'],
    s=sizes,
    cmap='viridis',
    alpha=0.7,
    edgecolors='k',
    linewidths=0.3,
    transform=proj,
    zorder=5
)

cbar = plt.colorbar(sc, ax=ax, shrink=0.6, pad=0.02, label='Contagem')
ax.gridlines(draw_labels=True, linewidth=0.3, alpha=0.5, linestyle='--')
ax.set_title('Distribuição Espacial dos "Absurdos"', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

# aqui vamos pegar o caso mais emblemático... aquela coordenada que pediu a maior quantidade de seguros...
absurdos.iloc[0]

# vamos ver que tanto de COP foi pedida para a primeira coordenada do absurdo...
coord = absurdos[['longitude_centroide', 'latitude_centroide']].iloc[0].values
df[(df['longitude_centroide'] == coord[0]) & (df['latitude_centroide'] == coord[1])]

"""Hipotese sobre esses resultados:
É possível que os pedidos foram realizados por uma coperativa... colocando essas coordenadas no google maps, caímos numa localidade específica...
"""

# Então vamos filtrar por um único plantio por latitude e longitude
contagem_filtrada = (df
    .groupby(['longitude_centroide', 'latitude_centroide'])['dt_comunicacao'] # além das coordenadas, agora também filtramos a data
    .nunique() # ao invés de contar, pegamos as datas únicas
    .reset_index(name='contagem')
    .sort_values('contagem', ascending=False)
)
contagem_filtrada

# repetindo o mesmo mapa para essas coordenadas
# Filtrando contagem > 2
contagem_filtrada = contagem_filtrada[contagem_filtrada['contagem'] > 2]

# cria uma nova figura
fig, ax = plt.subplots(figsize=(12, 10), subplot_kw={'projection':proj})

# Limites do mapa (baseado nos dados com margem)
margin = 1
ax.set_extent([
    contagem_filtrada['longitude_centroide'].min() - margin,
    contagem_filtrada['longitude_centroide'].max() + margin,
    contagem_filtrada['latitude_centroide'].min() - margin,
    contagem_filtrada['latitude_centroide'].max() + margin
], crs=ccrs.PlateCarree())

# Features do mapa
ax.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='k')
ax.add_feature(cfeature.STATES, linewidth=0.3, edgecolor='k', linestyle='--')
ax.add_feature(cfeature.COASTLINE, linewidth=0.5)
ax.add_feature(cfeature.LAND, facecolor='#f0f0f0')
ax.add_feature(cfeature.OCEAN, facecolor='#d4e6f1')

sc = ax.scatter(
    contagem_filtrada['longitude_centroide'],
    contagem_filtrada['latitude_centroide'],
    c='k',
    s=contagem_filtrada['contagem']*10,
    alpha=0.25,
    edgecolors='none',
    linewidths=0,
    transform=proj,
    zorder=5
)

ax.gridlines(draw_labels=True, linewidth=0.3, alpha=0.5, linestyle='--')
ax.set_title('Distribuição Espacial das localidades que pediram\nseguro pelo menos 3 vezes ao longo dos anos', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

# Vamos transformar isso num mapa interativo...
import folium
from folium.plugins import HeatMap

# Centro do mapa
center_lat = contagem_filtrada['latitude_centroide'].mean()
center_lon = contagem_filtrada['longitude_centroide'].mean()

m = folium.Map(location=[center_lat, center_lon], zoom_start=6)

# Dados para o heatmap: [lat, lon, peso]
heat_data = contagem_filtrada[['latitude_centroide', 'longitude_centroide', 'contagem']].values.tolist()

HeatMap(heat_data, radius=10, blur=5, max_zoom=13).add_to(m)

m

"""Vamos ao que é o ponto central: Buscar uma coordenada de interesse e ver se o pedido é coerente com os dados meteorológicos"""

coord = contagem_filtrada[['longitude_centroide', 'latitude_centroide']].iloc[0].values
lat = coord[1]
lon = coord[0]
df_azarado = df[(df['longitude_centroide'] == lon) & (df['latitude_centroide'] == lat)]
df_azarado

# Destacando essa essa localidade no heatmap Folium
folium.Marker([lat,lon], popup="Local COP recorrente").add_to(m)
m

# Aqui vamos fazer algumas "mágicas" com Linux/Bash/Shell
!ls

# Para acessar o arquivo, precisa usar o caminho completo, pois o `!cd` não afeta as células seguintes.
!head /content/drive/MyDrive/INMET/2024/INMET_S_SC_A806_FLORIANOPOLIS_01-01-2024_A_31-12-2024.CSV

# quero criar um arquivo só com as latitudes e longitude das estações
# para isso vou combinar uma sequência de comandos...
!grep 'CODIGO' -A2 /content/drive/MyDrive/INMET/2024/*.CSV | sed 's/^.*CSV//; s/,/./g' | cut -d';' -f2 | grep -v '^--' | paste - - - -d',' > coordenadas-inmet.csv

!ls

!head coordenadas-inmet.csv

# Buscando coord proximas
inmet_coords = pd.read_csv('coordenadas-inmet.csv', header=0, names=['cod', 'latitude', 'longitude'])
inmet_coords

#equção de Harvesine
import math

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # raio da Terra em km
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)

    a = math.sin(dphi / 2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2)**2
    return 2 * R * math.asin(math.sqrt(a))

# Aplicando a função no nosso ponto de interesse e NO DATA FRAME DE LOCALIDADES DO INMET
inmet_coords['estacoes_proximas'] = inmet_coords.apply(lambda row: haversine(lat, lon, row['latitude'], row['longitude']), axis=1).sort_values()

inmet_coords.sort_values('estacoes_proximas')

top3 = inmet_coords.sort_values('estacoes_proximas').head(3)

# inclue esse top 3 estações próximas no mapa Folium, só pra gente ter uma noção de distância...
for _, row in top3.iterrows():
  print(row['cod'], row['latitude'], row['longitude'], row['estacoes_proximas'])
  folium.Marker(
        [row['latitude'], row['longitude']],
        popup=f"{ row['cod']} - {row['estacoes_proximas']:.1f} km",
        tooltip=row['cod'],
        icon=folium.Icon(color="orange", icon="cloud")
    ).add_to(m)

m

# Agora sim, sabemos quem são os códigos das estações próximas... logo, vamos abrir os arquivos dessas estações...
top3.cod.to_list()

# Agora sim, sabemos quem são os códigos das estações próximas... logo, vamos abrir os arquivos dessas estações...
!head /content/drive/MyDrive/INMET/*/*A837*.CSV

import glob
# Nomes padronizados para todas as 19 colunas
COLUNAS = [
    'DATA', 'HORA',
    'PREC',          # Precipitação total horária (mm)
    'PATM',          # Pressão atmosférica estação (mB)
    'PATM_MAX',      # Pressão atm máxima hora ant (mB)
    'PATM_MIN',      # Pressão atm mínima hora ant (mB)
    'RAD',           # Radiação global (KJ/m²)
    'TEMP',          # Temperatura bulbo seco (°C)
    'TD',            # Temperatura ponto de orvalho (°C)
    'TMAX',          # Temperatura máxima hora ant (°C)
    'TMIN',          # Temperatura mínima hora ant (°C)
    'TD_MAX',        # Temp orvalho máxima hora ant (°C)
    'TD_MIN',        # Temp orvalho mínima hora ant (°C)
    'UR_MAX',        # Umidade relativa máxima (%)
    'UR_MIN',        # Umidade relativa mínima (%)
    'UR',            # Umidade relativa horária (%)
    'VENTO_DIR',     # Direção do vento (graus)
    'VENTO_RAJ',     # Rajada máxima (m/s)
    'VENTO_VEL',     # Velocidade horária (m/s)
]


STN = []
for stn in top3.cod.to_list():
    # Corrigindo o caminho para incluir o Google Drive montado
    files = glob.glob(f'/content/drive/MyDrive/INMET/*/*{stn}*.CSV')
    for f in files:
        df_stn = pd.read_csv(f, encoding='latin1', sep=';', decimal=',', skiprows=8)
        print(f)

        # Remove última coluna vazia (trailing ;)
        df_stn = df_stn.loc[:, ~df_stn.columns.str.startswith('Unnamed')]

        # renomeia as colunas de acordo com a posição
        df_stn.columns = COLUNAS[:len(df_stn.columns)]

        # Normaliza colunas da data e da hora
        df_stn.rename(columns={df_stn.columns[0]: 'DATA', df_stn.columns[1]: 'HORA'}, inplace=True)

        # Garante que é Series (não DataFrame)
        df_stn['HORA'] = (df_stn['HORA']
                          .astype(str)
                          .str.strip()
                          .str.replace(' UTC', '', regex=False)
                          .str.replace(r'^(\d{2})(\d{2})$', r'\1:\2', regex=True))

        df_stn['DATA'] = df_stn['DATA'].astype(str).str.replace('/', '-')
        df_stn['COD'] = stn
        df_stn.index = pd.to_datetime(df_stn['DATA'] + ' ' + df_stn['HORA'])

        STN.append(df_stn)

df_all = pd.concat(STN)

df_all



# Filtrando df_all para incluir apenas dados a partir de 2014
df_filtered = df_all[df_all.index.year >= 2014]

print(f"Shape do DataFrame original: {df_all.shape}")
print(f"Shape do DataFrame filtrado (a partir de 2014): {df_filtered.shape}")
display(df_filtered.head())

df_prec = df_filtered[['COD','PREC']]
df_prec

df_prec = df_prec.pivot_table(index=df_prec.index, columns='COD', values='PREC')
df_prec

df_azarado

# Agora vamos somar a precipitação no período do azar
evento_azarado = df_azarado.iloc[0]
dt_inicio_evento = evento_azarado['dt_inicio_evento']
dt_fim_evento = evento_azarado['dt_fim_evento']
df_prec.loc[dt_inicio_evento:dt_fim_evento].sum()

# quantos dias de azar?
import datetime as dt
dt_inicio_evento = dt.datetime.strptime(dt_inicio_evento,'%Y-%m-%d')
dt_fim_evento = dt.datetime.strptime(dt_fim_evento,'%Y-%m-%d')

print(dt_fim_evento - dt_inicio_evento)

# chuva total da safra
dt_plantio = evento_azarado['dt_inicio_plantio']
dt_colheita = evento_azarado['dt_fim_colheita']
df_prec.loc[dt_plantio:dt_colheita].sum()

#Vamos estimar o estádio fenológico dessa soja, com base no acúmulo de graus dia
import numpy as np

# Parâmetros da soja
TB = 10   # Temperatura base (°C)
TM = 38   # Temperatura máxima (°C) - acima disso, não contribui

def graus_dia_diario(tmax, tmin, tb=TB, tm=TM):
    """
    Calcula graus-dia diário pelo método da média simples com limites.

    GD = ((Tmax + Tmin) / 2) - Tb

    Com correções:
    - Se Tmax > Tm, usa Tm
    - Se Tmin < Tb, usa Tb
    - Se GD < 0, retorna 0
    """
    tmax = np.minimum(tmax, tm)
    tmin = np.maximum(tmin, tb)
    gd = ((tmax + tmin) / 2) - tb
    return np.maximum(gd, 0)


def graus_dia_acumulado(df, col_tmax='TMAX', col_tmin='TMIN', col_prec='PREC',
                         data_semeadura=None, gd_maturacao=1500):
    """
    Calcula GD acumulado e precipitação acumulada por fase fenológica.
    """
    # Reamostra para diário
    df_dia = df.resample('D').agg({col_tmax: 'max', col_tmin: 'min', col_prec: 'sum'})
    df_dia.dropna(subset=[col_tmax, col_tmin], inplace=True)

    # Filtra a partir da semeadura
    if data_semeadura:
        df_dia = df_dia.loc[data_semeadura:]

    # Calcula GD
    df_dia['GD'] = graus_dia_diario(df_dia[col_tmax], df_dia[col_tmin])
    df_dia['GD_ACUM'] = df_dia['GD'].cumsum()

    # Fases fenológicas
    fases = {
        'VE - Emergência':         50,
        'V2 - 2º nó':            130,
        'V4 - 4º nó':            230,
        'R1 - Início floração':   550,
        'R3 - Início enchimento': 750,
        'R5 - Enchimento grão':   950,
        'R7 - Maturidade fisiol.':1250,
        'R8 - Maturação plena':   gd_maturacao,
    }

    # Identifica data de cada fase
    df_dia['FASE'] = ''
    datas_fases = {}
    for fase, gd_ref in fases.items():
        mask = df_dia['GD_ACUM'] >= gd_ref
        if mask.any():
            idx = mask.idxmax()
            df_dia.loc[idx, 'FASE'] = fase
            datas_fases[fase] = idx

    # Calcula precipitação acumulada entre fases
    fases_ordem = list(fases.keys())
    prec_por_fase = {}
    for i, fase in enumerate(fases_ordem):
        if fase not in datas_fases:
            break
        dt_ini = datas_fases[fases_ordem[i - 1]] if i > 0 and fases_ordem[i - 1] in datas_fases else df_dia.index[0]
        dt_fim = datas_fases[fase]
        prec_por_fase[fase] = {
            'data_inicio': dt_ini,
            'data_fim': dt_fim,
            'dias': (dt_fim - dt_ini).days,
            'tmax': df_dia.loc[dt_ini:dt_fim, col_tmax].max(),
            'prec_mm': df_dia.loc[dt_ini:dt_fim, col_prec].sum(),
            'gd_acum': df_dia.loc[dt_fim, 'GD_ACUM'],
        }

    df_fases = pd.DataFrame(prec_por_fase).T
    df_fases.index.name = 'FASE'

    return df_dia, fases, df_fases

# Supondo que df_all que virou df_filtered já existe com TMAX, TMIN por estação
# Para uma estação específica:
stn = 'A837'
df_stn = df_filtered[df_filtered['COD'] == 'A837'][['TMAX', 'TMIN', 'PREC']].copy()

#dt_plantio = dt.datetime.strptime(dt_plantio, '%Y-%m-%d')
data_semeadura=dt_plantio


df_gd, fases, df_fases = graus_dia_acumulado(df_stn, data_semeadura=dt_plantio)

# Mostra fases atingidas
print("-" * 75)
print(f"stação: {stn} | Semeadura: {data_semeadura}")
print("-" * 75)
df_fases

print(f'Evento Adverso: {dt_inicio_evento} a {dt_fim_evento}, total de {dt_fim_evento-dt_inicio_evento}')
dt_meio = dt_inicio_evento + (dt_fim_evento - dt_inicio_evento) / 2
print(dt_meio)
df_fases[(df_fases['data_inicio'] <= dt_meio) & (df_fases['data_fim'] >= dt_meio)]

# Valores hipotéticos precipitação e GDD por estádio
prec_esperada = {
    'VE - Emergência':          25,   # ~20–30 mm apenas na germinação/emergência
    'V2 - 2º nó':               30,   # mm adicionais em VE→V2
    'V4 - 4º nó':               35,   # mm adicionais em V2→V4
    'R1 - Início floração':     53,   # mm adicionais em V4→R1
    'R3 - Início enchimento':  117,   # mm adicionais em R1→R3 (~metade de R1→R5)
    'R5 - Enchimento grão':    125,   # mm adicionais em R3→R5 (completa R1→R5 = 242 mm)
    'R7 - Maturidade fisiol.': 132,   # mm adicionais em R5→R7
    'R8 - Maturação plena':     43,   # mm adicionais em R7→R8
}

fases_gdd = {
    'VE - Emergência':          50,
    'V2 - 2º nó':             130,
    'V4 - 4º nó':             230,
    'R1 - Início floração':    550,
    'R3 - Início enchimento':  750,
    'R5 - Enchimento grão':    950,
    'R7 - Maturidade fisiol.':1250,
    'R8 - Maturação plena':   1500,
}

# Vizualizando todos esses dados
import matplotlib.pyplot as plt
import numpy as np


fases = list(fases_gdd.keys())
gdd_literatura = list(fases_gdd.values())
gdd_observado = df_fases['gd_acum'].values

# Extract precipitation values in the correct order for prec_esperada
prec_esperada_list = [prec_esperada[fase] for fase in fases]
# Extract observed precipitation from df_fases
prec_observada = df_fases['prec_mm'].values

x = np.arange(len(fases))

fig, ax = plt.subplots(figsize=(14, 6))
ax2 = ax.twinx()

# Barras de precipitação
width = 0.35
bars1 = ax.bar(x - width/2, prec_esperada_list, width, label='Prec. Esperada', color='tab:blue', edgecolor='white', zorder=3)
bars2 = ax.bar(x + width/2, prec_observada, width, label='Prec. Observada', color='tab:orange', edgecolor='white', zorder=3)

for bar in bars1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
            f'{bar.get_height():.0f}', ha='center', va='bottom', fontsize=8, color='grey')
for bar in bars2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
            f'{bar.get_height():.0f}', ha='center', va='bottom', fontsize=8, color='k')

# Linhas de GDD
ax2.plot(x, gdd_literatura, color='grey', marker='s', linewidth=2.5, markersize=8,
         linestyle='--', label='GDD Literatura', zorder=4)
ax2.plot(x, gdd_observado, color='k', marker='o', linewidth=2.5, markersize=8,
         label='GDD Observado', zorder=4)

for i in range(len(fases)):
  ax2.text(i - 0.15, gdd_literatura[i] + 30, f'{gdd_literatura[i]:.0f}',
          ha='center', fontsize=8, color='grey', fontweight='bold',
          bbox=dict(boxstyle='round,pad=0.2', facecolor='white', edgecolor='grey', alpha=0.8))
  ax2.text(i + 0.15, gdd_observado[i] - 50, f'{gdd_observado[i]:.0f}',
          ha='center', fontsize=8, color='k', fontweight='bold',
          bbox=dict(boxstyle='round,pad=0.2', facecolor='white', edgecolor='k', alpha=0.8))

ax.set_xlabel('Fase Fenológica')
ax.set_ylabel('Precipitação (mm)')
ax2.set_ylabel('GDD Acumulado (°C·dia)')
ax.set_title('Precipitação e GDD por Fase Fenológica: Literatura vs Observado', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(fases, rotation=30, ha='right', fontsize=9)

lines1, labels1 = ax.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax.legend(lines1 + lines2, labels1 + labels2, loc='upper left')

ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""Observando o Dash realmente em uma fase critica para soja como o enchimento de grão vemos uma precipitação abaixo do esperado, perdurando até inicio da maturação"""

print(lat, lon)